### ISSUE TITLE
Missing readme and repo description

### ISSUE THREAD

**Issue by Mr0grog** [ipfs/go-ipfs-config#1]
This repo really needs a repo description and a readme. (Note also the readme should follow [the IPFS licensing policy](https://github.com/ipfs/community/blob/64d3c9b681ea85b6a4ce90e9ee248efe3b9338a7/docs/licensing-policy.md). It’s pretty hard to understand what this is for or how it fits in without those.

**Comment by lidel** [comment]
go-ipfs-config got merged into go-ipfs repo: https://github.com/ipfs/go-ipfs/tree/master/config
