### ISSUE TITLE
Move this repo back  into go-ipfs

### ISSUE THREAD

**Issue by BigLep** [ipfs/go-ipfs-config#151]
**Done criteria:** this repo's content is moved into ipfs/go-ipfs and this repo is archived/redirected accordingly.
**Why important:** makes it harder for contributors as have to have PRs often in this repo and ipfs/go-ipfs

**Comment by laurentsenta** [comment]
I took a shot at this here: https://github.com/ipfs/go-ipfs/pull/8756

Two questions:

- Is the timing right to push this further?
- Should we sync with other projects that relies on this?

The package is imported by 200+ other packages,
https://pkg.go.dev/github.com/ipfs/go-ipfs-config?tab=importedby

The ipfs ones:

-   [github.com/ipfs/ipfs-cluster](https://pkg.go.dev/github.com/ipfs/ipfs-cluster)
-   [github.com/ipfs/ipfs-cluster/api/common](https://pkg.go.dev/github.com/ipfs/ipfs-cluster/api/common)
-   [github.com/ipfs/ipfs-cluster/api/ipfsproxy](https://pkg.go.dev/github.com/ipfs/ipfs-cluster/api/ipfsproxy)
-   [github.com/ipfs/ipfs-ds-convert/testutil](https://pkg.go.dev/github.com/ipfs/ipfs-ds-convert/testutil)
-   [github.com/ipfs/ipget](https://pkg.go.dev/github.com/ipfs/ipget)
-   [github.com/ipfs/iptb-plugins](https://pkg.go.dev/github.com/ipfs/iptb-plugins)
-   [github.com/ipfs/iptb-plugins/browser](https://pkg.go.dev/github.com/ipfs/iptb-plugins/browser)
-   [github.com/ipfs/iptb-plugins/docker](https://pkg.go.dev/github.com/ipfs/iptb-plugins/docker)
-   [github.com/ipfs/iptb-plugins/local](https://pkg.go.dev/github.com/ipfs/iptb-plugins/local)
-   [github.com/ipfs/rainbow](https://pkg.go.dev/github.com/ipfs/rainbow)
-   [github.com/ipfs/testground/sdk/iptb](https://pkg.go.dev/github.com/ipfs/testground/sdk/iptb)

**Comment by aschmahmann** [comment]
@hsanjuan do you have any concerns on how this will impact ipfs-cluster?

Generally I think this is a good idea and should be fine. As it is basically every change to that repo has come from people working on go-ipfs and the repo is pretty tied to go-ipfs. If we feel the need for some backwards compatibility we can always choose to alias go-ipfs-config into go-ipfs/config with a deprecation to let people lag behind a little while they update.

**Comment by hsanjuan** [comment]
> @hsanjuan do you have any concerns on how this will impact ipfs-cluster?

I think the project will survive if this is merged back.
